@startuml
left to right direction
skinparam packageStyle rect 
skinparam actorStyle Hollow

title Un diagrama de casos d'ús per a TripUB

actor Usuari as usuari
actor Persona as persona

rectangle TripUB {

usecase (UC1. Sign UP)  as UC1 #aliceblue;line:blue;line.bold;text:blue
usecase (UC2. Sign IN) as UC2  #aliceblue;line:blue;line.bold;text:blue
usecase (UC3. Visualitzar Llista Rutes) as UC3  #aliceblue;line:blue;line.bold;text:blue
usecase (UC4. Cercar Rutes ) as UC4#aliceblue;line:blue;line.bold;text:blue
usecase (UC4.3 Cercar Rutes Per Transport Recomanat) as UC43#aliceblue;line:blue;line.bold;text:blue
usecase (UC4.2 Cercar Rutes Per Localitat) as UC42 #aliceblue;line:blue;line.bold;text:blue
usecase (UC4.1 Cercar Rutes Per Comarca ) as UC41 #aliceblue;line:blue;line.bold;text:blue
usecase (UC4.4 Cercar Rutes Per Temps de Durada) as UC44#aliceblue;line:blue;line.bold;text:blue
usecase (UC5 Començar Ruta) as UC5
usecase (UC6 Finalitzar Ruta) as UC6
usecase (UC7 Començar Track) as UC7
usecase (UC8 Afegir punt de control a un Track) as UC8
usecase (UC9 Finalitzar Track) as UC9
usecase (UC10 Mostrar Estadistiques d'un Track) as UC10
usecase (UC11 Crear Grup) as UC11
usecase (UC12 Afegir-se al grup) as UC12
usecase (UC13 Marxar del grup) as UC13
usecase (UC14 Calcular Ranking Grup Track) as UC14




persona -- UC2


UC1 -> UC2 : <<include>>
UC7 -> UC5 : <<extends>>
UC5 -> UC6 : <<include>>
UC7 -> UC9 : <<include>>
UC8 --> UC7 : <<extends>>
UC10 -> UC9 : <<extends>>
UC13 -> UC12 : <<extends>>
UC13 -> UC11 : <<extends>>
UC12 -> UC11 : <<extends>>

UC4 <|-- UC41
UC4 <|-- UC42
UC4 <|-- UC43
UC4 <|-- UC44

persona -- UC4
persona -- UC3
persona -- UC5

persona -- UC10
persona -- UC11
persona -- UC14






usuari -- UC1
}
@enduml



